# Generated by Django 3.2.6 on 2021-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admission_number', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=50)),
            ],
        ),
    ]
